### ISSUE TITLE
add .resinci.yml.example

### ISSUE THREAD

**Issue by somombo** [balena-io/balena-google-apps-script-sheet-skeleton#19]
```yaml
# for example
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "12"
        - "14"
```
